#SPDX-License-Identifier: MIT-0
---
- name: Install useful packages
  ansible.builtin.apt:
    name:
      - curl
      - htop
      - vim
    state: present
    update_cache: true
# tasks file for roles/common
